<a href="https://colab.research.google.com/github/riad234/IPB-Semester2-PengenalanPola/blob/LKP-3/Eksperimen_LKP3_Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load Dataset
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
data = pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Encoding Label
# Spam = 1
# Ham (non-spam) = 0

data['label'] = data['label'].map({'ham': 0, 'spam': 1})
data.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data['message'],
    data['label'],
    test_size=0.2,
    random_state=42
)

In [ ]:
# Feature Extraction (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
# Training Naïve Bayes
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
# Evaluasi Model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.97847533632287

Confusion Matrix:
 [[966   0]
 [ 24 125]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       1.00      0.84      0.91       149

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [ ]:
# Implementasi CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Vectorisasi dengan CountVectorizer
count_vectorizer = CountVectorizer(stop_words='english')

X_train_count = count_vectorizer.fit_transform(X_train)
X_test_count = count_vectorizer.transform(X_test)

# Training model
model_count = MultinomialNB()
model_count.fit(X_train_count, y_train)

# Prediksi
y_pred_count = model_count.predict(X_test_count)

# Evaluasi
print("Accuracy (CountVectorizer):", accuracy_score(y_test, y_pred_count))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_count))
print("\nClassification Report:\n", classification_report(y_test, y_pred_count))

Accuracy (CountVectorizer): 0.9883408071748879

Confusion Matrix:
 [[961   5]
 [  8 141]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.95      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [ ]:
# Ambil Probabilitas Kata dari Model
import numpy as np
import pandas as pd

# Ambil nama fitur (kata)
feature_names = count_vectorizer.get_feature_names_out()

# Ambil log probability dari model
log_probs = model_count.feature_log_prob_

# Class 0 = ham
# Class 1 = spam

# Ambil 10 kata paling besar probabilitasnya untuk spam
top_spam_indices = np.argsort(log_probs[1])[-10:]
top_spam_words = feature_names[top_spam_indices]

# Ambil 10 kata paling besar probabilitasnya untuk ham
top_ham_indices = np.argsort(log_probs[0])[-10:]
top_ham_words = feature_names[top_ham_indices]

print("Top 10 Spam Words:")
print(top_spam_words)

print("\nTop 10 Ham Words:")
print(top_ham_words)

Top 10 Spam Words:
['prize' 'www' 'claim' 'reply' 'stop' 'mobile' 'text' 'ur' 'txt' 'free']

Top 10 Ham Words:
['come' 'good' 'know' 'got' 'ur' 'll' 'ok' 'just' 'lt' 'gt']